Pass coordinates by reference in 3D and 4D functions
OSGeo/proj.4 pull request #1351
Opened 2019-03-23 18:29 UTC by rouault

This fixes cppcheck master warnings.
This could have a (likely tiny) performance advantage by saving useless
copies of the xyz/xyzt argument.

2019-03-26 17:31 UTC, kbevers commented
Is this still work-in-progress?

I don't think I understand the reason for this. What are the warnings that are avoided by this fix? It somehow seems a bit unnatural to me to pass by reference here, but I can't really explain why. Just one of those things, I guess :-) 
Also, is it not necessary to give the 2D-functions the same treatment?

2019-03-26 18:35 UTC, rouault commented
> Is this still work-in-progress?

yes, until I manage find the motivation to look at the disassembly to see if that doesn't worsen things at least.

> I don't think I understand the reason for this. What are the warnings that are avoided by this fix?

cppcheck (more recent versions than the one used in CI) warns as soon as a C++ struct/class instance is passed by value instead of reference. The rationale is that it saves copying of objects (passing by reference is under-the-hood similar as passing a pointer to the structure), and thus can help performance.

>  is it not necessary to give the 2D-functions the same treatment?

in theory yes, but cppcheck doesn't detect it (it is an inperfect tool). In the case of the 2D functions, the size of the XY/LP structure is just 16 bytes. Passing by reference on 64bit builds would be 8 bytes, so the gain would not be that much and basically all files under src/projections/ should be changed, so a lot of effort.

2019-03-26 18:45 UTC, kbevers commented
> yes, until I manage find the motivation to look at the disassembly to see if that doesn't worsen things at least.

Right, doesn't sound like the most exciting thing to do :-)

> The rationale is that it saves copying of objects (passing by reference is under-the-hood similar as passing a pointer to the structure), and thus can help performance.

Yes, I got the part about the performance, just not that that was the problem. It just sounded like a nice side effect. We have been getting a bunch of performance complaints lately (valid or not) so it may be a good idea to focus on that for a bit.

> basically all files under src/projections/ should be changed, so a lot of effort.

This will have to be done sooner or later anyway[0], so we might as well coordinate the effort so that it only requires one pass. 

[0] In the not-so-distant future all operations should be 4D, and 4D only.

2019-03-26 18:51 UTC, rouault commented
> so it may be a good idea to focus on that for a bit.

That would be just a micro-optimization. Nothing that I'd expect to have measurable consequences in performance profiles... The main focus was to have clean cppcheck output.

2019-03-27 10:31 UTC, busstoptaktik commented
> That would be just a micro-optimization. Nothing that I'd expect to have measurable consequences in performance profiles

I did some timing checks some years ago, before introducing `proj_trans()`.

Passing the PJ_COORD by reference made absolutely no difference on my setup at that time (I do not remember the details, but I am pretty sure that even on a PDP-11 the difference would be immaterial).

Also, the return value is returned by value, so some struct-sized copying is done anyway.

2019-07-14 22:48 UTC, CherryKitty requested changes
Please fix to original content. I am not a coder. This is taking me litterally forever in a day to try and figure out. And preventing me from making art.

2019-10-29 15:11 UTC, rouault commented
Dropping this PR. scripts/cppcheck.sh has been adapted to ignore the related warnings

2019-10-29 15:11 UTC, closed without merging