Add rotation support to the HEALPix projection
OSGeo/proj.4 pull request #1638
Opened 2019-09-25 06:18 UTC by Schneegans

# Motivation

At the German Aerospace Center (DLR) we are developing a VR-Framework called [CosmoScout VR](https://github.com/cosmoscout/cosmoscout-vr). This software can render highly detailed level-of-detail planetary bodies in real-time. The required surface tiles are downloaded from a [MapServer](https://mapserver.org/) instance and are provided in the HEALPix projection. The advantage is, that the data density is equal all around the globe without any singularities at the poles.

However, in order to retrieve the HEALPix base patches as image tiles, the map has to be rotated by 45°. Here is an image from our documentation which illustrates this with the figures in the center row:

![image](https://raw.githubusercontent.com/cosmoscout/cosmoscout-vr/develop/docs/img/coordinate-systems.jpg)

# Implemented Changes

The file `src/projections/healpix.cpp` has been changed to accept an optional `+rot=` parameter, which has to be given in degrees and defaults to zero.

# Usage

We use this in a custom projection like this and it works very well:

```
<900914> +proj=healpix +lon_0=0 +x_0=2.5 +y_0=2.5 +a=0.900316316157106 +rot=45 +no_defs <>
```

2019-09-25 06:51 UTC, kbevers requested changes
Very interesting. I can't see why we shouldn't include this. Before we do that though you need to update the documentation. Start here `https://github.com/OSGeo/PROJ/blob/master/docs/source/operations/projections/healpix.rst`.

Also, does it make sense to add the rotation parameter to the rHEALPix projection as well?

2019-09-25 06:51 UTC, kbevers commented on src/projections/healpix.cpp
> +static PJ_XY rotate(PJ_XY p, double a) {
I suggest you use `angle` instead of `a` here. Makes it immediately clear what's going on

2019-09-25 06:51 UTC, kbevers commented on src/projections/healpix.cpp
> +    Q->rot = pj_param(P->ctx, P->params,"drot").f * M_PI / 180.0;
Improve readability a bit:

```suggestion
	double angle = pj_param(P->ctx, P->params,"drot").f;
    Q->rot = PJ_TORAD(angle);
```

2019-09-25 08:22 UTC, rouault commented on docs/source/operations/projections/healpix.rst
> +    Rotation of the HEALPix map in degrees.
I believe it should be explained that the rotation is done in the cartesian / projected coordinate space, and what is the convention for the orientation (trigonometric ? clockwise ?)

2019-09-25 08:24 UTC, rouault commented
One thought I add is that such a +rot parameter could be something generic to all projections, such as +x_0, +y_0. But we could potentially move that to generic code at a later stage if we find that several projections need this.
Was wondering if rot_xy might not be more expressive about in which coordinate space the rotation is done ?

2019-09-25 08:28 UTC, rouault commented
Extending heapix tests in test/gie/builtins.gie to test this new parameter would also be welcome

2019-09-25 08:29 UTC, kbevers commented
> One thought I add is that such a +rot parameter could be something generic to all projections, such as +x_0, +y_0. But we could potentially move that to generic code at a later stage if we find that several projections need this.

Like a rotation operation? Something like
```
+proj=pipeline +step +proj=healpix ... +step +proj=rot +angle=45.0
```
perhaps?

2019-09-25 08:55 UTC, Schneegans commented
Thanks for the feedback! I'll update the PR as soon as possible.

> Also, does it make sense to add the rotation parameter to the rHEALPix projection as well?

I like the idea of supporting this parameter for all projections, however for the rHEALPix projection I don't see any particular use case.

> Extending heapix tests in test/gie/builtins.gie to test this new parameter would also be welcome

I will do this. Are these tests auto-generated? Or are the numbers somehow computed by hand? Or shall I just use the current implementation and assume that the values are correct?

2019-09-25 09:01 UTC, kbevers commented
> Or shall I just use the current implementation and assume that the values are correct?

Presumably you have tested elsewhere that your implementation actually works. If that is the case, then yes, just use values generated by the new code in the tests. They mainly exist as regression tests. When test material from a difference source is available, like test coordinates from a scientific paper, we like to use those as well but that is not possible in this case.

2019-09-25 09:02 UTC, rouault commented
> Like a rotation operation? Something like

yeah, I was thinking to that. Could be useful as an operation, but the issue is as soon as you define a pipeline, this is no longer a CRS definition, and you'll struggle using that in a Mapserver context where you define a CRS for your project or layer

>  Are these tests auto-generated? Or are the numbers somehow computed by hand? Or shall I just use the current implementation and assume that the values are correct?

manually. Just add a new entry and run "make check". It will give you the output result it found if not consistent with the one you put, so you can bootstrap with dummy output values, and use the ones it will get to you. But you're supposed to do some validation of your input/output tuples ;-)

2019-09-25 09:26 UTC, kbevers commented
> yeah, I was thinking to that. Could be useful as an operation, but the issue is as soon as you define a pipeline, this is no longer a CRS definition, and you'll struggle using that in a Mapserver context where you define a CRS for your project or layer

I see that as a Mapserver problem :-) But seriously, this could be dealt with by setting up a WKT string that includes a rotation step, no? Provided that the rotation operation is put in the WKT machinery of course.

2019-09-25 09:40 UTC, rouault commented
> I see that as a Mapserver problem :-)

yeah, which means my problem at some point (I've a port of MapServer to PROJ 6 API almost ready, and this wasn't an easy ride. And MapServer will still continue to use heavily PROJ strings for CRS in a foreseable future)

> this could be dealt with by setting up a WKT string that includes a rotation step, no?

Yes, likely a DerivedProjectedCRS with a deriving conversion being a rotation. They will have derived projected CRS in EPSG v10 (see https://www.iogp.org/blog/epsg/upgrade-of-epsg-dataset-data-model/), but I haven't looked if the EPSG guidance note 7-2 describes a rotation method. Probably. Actually the +proj=affine ( https://proj.org/operations/transformations/affine.html ) could already be used for that (not completely sure to remember why it's classified as a transformation rather than a conversion, but whatever)

~~~~~~

To come back to this pull request, what is the rotation center: (0, 0) or (x_0, y_0) ?

2019-09-25 10:44 UTC, busstoptaktik commented
> Like a rotation operation? Something like

We have that already, I believe, as a special case of the 4 parameter Helmert

2019-09-25 11:00 UTC, kbevers commented
> We have that already, I believe, as a special case of the 4 parameter Helmert

Correct. Although you have to give the rotation in arc seconds

2019-09-25 11:26 UTC, Schneegans commented
> To come back to this pull request, what is the rotation center: (0, 0) or (x_0, y_0) ?

I think the correct answer to this question is `(x_0, y_0)`.

The first figure in the second row of the picture I included above shows a result of `+x_0=2.5 +y_0=2.5 +rot_xy=45` (plus some scaling).

2019-09-25 11:52 UTC, rouault commented on test/gie/builtins.gie
> +accept  2 1
to test just that parameter, one expect/accept tuple should be enough.
But I find it more convincing to use the expect value as the acept value of the `direction inverse` case. This shows correct implementation of the roundtripping

2019-09-25 11:56 UTC, kbevers commented on docs/source/operations/projections/healpix.rst
> +.. option:: +rot_xy
It should be mentioned when this was introduced:

```suggestion
.. option:: +rot_xy

  .. versionadded:: 7.0.0
```

2019-10-01 08:52 UTC, Schneegans commented
Are there any updates for this one? I hope that I resolved all suggested changes :smile:

2019-10-01 09:43 UTC, rouault commented
Looks good to me. I let @kbevers do his check. (we should use "squash and merge" to fold the commits)

2019-10-01 12:06 UTC, merged

2019-10-01 12:06 UTC, kbevers commented
Looks good to me