ENH: Added temporal, engineering, and parametric PJ_TYPE enumerations
OSGeo/proj.4 pull request #2274
Opened 2020-06-27 01:18 UTC by snowman2

- [x] Closes #2273
 - [x] Tests added
 - [x] Added clear title that can be used to generate release notes
 - [ ] Fully documented, including updating `docs/source/*.rst` for new API

2020-06-27 01:25 UTC, snowman2 commented
@rouault there is the generic `DATUM` type. Is there a datum type that isn't covered by this that might pop up?

2020-06-27 02:58 UTC, snowman2 commented
Any chance of adding this in 7.1?

2020-06-27 05:46 UTC, kbevers commented
> Any chance of adding this in 7.1?

Not unless there's an RC3 - this PR in itself is not enough to trigger that.

2020-06-27 07:55 UTC, rouault requested changes

2020-06-27 07:55 UTC, rouault commented on src/proj.h
> +    PJ_TYPE_TEMPORAL_DATUM,
those new values must be added at the end of the enumerations, otherwise this changes the ABI

2020-06-27 13:02 UTC, snowman2 commented
> Not unless there's an RC3 - this PR in itself is not enough to trigger that.

From the perspective of pyproj, it is definitely worth it. 7.1 is the minimum version for the next release. It is a change that will address some current bugs.🤞

2020-06-27 13:08 UTC, snowman2 commented
> It is a change that will address some current bugs.crossed_fingers

I guess we could export each object to PROJ JSON and check the type there if this isn't added in 7.1 ... not quite as nice of a solution, but it works.

2020-06-27 13:54 UTC, rouault commented
@kbevers Is this material for 7.1.1 backport ? asking since it extends the API

2020-07-05 17:49 UTC, kbevers commented
>  asking since it extends the API

Then no. A very similar situation is adressed in this SO post: https://stackoverflow.com/questions/27300561/does-adding-enumerators-into-enum-break-abi/

2020-07-06 09:26 UTC, merged