Add .zenodo.json [ci skip]
OSGeo/proj.4 pull request #3019
Opened 2022-01-12 22:25 UTC by rouault

Add a .zenodo.json to prepare for automatic DOI generation when releasing PROJ.

I've given a try with a tag created on that branch in my fork with the sandbox.zenodo.org service: https://sandbox.zenodo.org/record/994082 / https://sandbox.zenodo.org/account/settings/github/repository/rouault/PROJ

See GDAL discussion thread: https://lists.osgeo.org/pipermail/gdal-dev/2022-January/thread.html#55228

2022-01-12 22:31 UTC, kbevers requested changes

2022-01-12 22:31 UTC, kbevers commented on .zenodo.json
> +            "affiliation": "SDFE.dk",
```suggestion
            "affiliation": "Danish Agency for Data Supply and Efficiency",
```

2022-01-12 22:31 UTC, kbevers commented on .zenodo.json
> +            "affiliation": "SDFE.dk",
```suggestion
            "affiliation": "Danish Agency for Data Supply and Efficiency",
```

2022-01-12 23:14 UTC, nyalldawson commented on .zenodo.json
> +            "name": "Dawson, Nyall"
```suggestion
            "name": "Dawson, Nyall",
            "orcid": "0000-0001-9812-7584"
```

2022-01-13 00:14 UTC, rouault commented
oops I had forgotten Jerry Evenden because github doesn't know him. I put USGS as his affiliation. Not sure how to handle someone who is deceased.

2022-01-13 08:52 UTC, mwtoews commented
Updated orcid values for @QuLogic and @snowman2 .. hope these look correct!

2022-01-13 08:52 UTC, kbevers commented on .zenodo.json
> +            "name": "Evers, Kristian"
```suggestion
            "affiliation": "Danish Agency for Data Supply and Efficiency",
            "name": "Evers, Kristian",
            "orcid": "0000-0002-1310-4576"
```

2022-01-13 18:23 UTC, merged

2022-01-13 19:01 UTC, schwehr commented
Thanks @rouault .  Curious to see how the community actually uses this.

2022-01-18 10:42 UTC, kbevers commented
Do we have an actual DOI now? If yes, we've been asked to register it at https://wiki.osgeo.org/wiki/DOI

2022-01-18 10:50 UTC, rouault commented
> Do we have an actual DOI now?

not yet. The github integration I've enabled requires a new release to be issued so that the all-version DOI is generated. I've been told that we could do a manual upload of a past release to do that (MapServer and QGIS have just done that), but I fail to see how the DOI record of the github integration would then be connected with the one obtained through manual upload. I fear that we'd have to do a manual upload each time we issue a new release, which would a no-go as far as I'm concerned. Maybe that's just my ignorance of the system.
I've just been trying to simulate that situation on sandbox.zenodo.org having created initially a fake upload in https://sandbox.zenodo.org/record/997579 and done a github release of https://github.com/rouault/test_zenodo/releases/tag/v1.0 in https://sandbox.zenodo.org/account/settings/github/repository/rouault/test_zenodo, but the later seems to be stalled.

2022-01-18 11:01 UTC, kbevers commented
Alright, it will just have to wait then :-) Thanks for setting all of this up!