Add preliminary documentation of suffix based specification of units
OSGeo/proj.4 pull request #3346
Opened 2022-09-26 01:19 UTC by sval-dev

Add preliminary documentation of suffix based specification of units for input parameter values.

 - [X] Closes #3345
 - [X] Added clear title that can be used to generate release notes

2022-09-26 07:33 UTC, kbevers requested changes
Thanks for adding this! I've suggested a different wording of the example using the central meridian.

It would be great to mention this feature in the docs for each of the generic options where it is useful. Perhaps just a simple example of how to give the value as radian and a link back to the new section of the docs provided in this PR. I believe the relevant options are `+lon_0`, `+lat_0`, `+lat_1`, `lat_2` and `+lat_ts`. They described here: https://github.com/OSGeo/PROJ/tree/master/docs/source/operations/options

2022-09-26 07:33 UTC, kbevers commented on docs/source/usage/projections.rst
> +units as ``long=1.5708r`` (approximately).
Reworded to use a well-known projection parameter:

```suggestion
Example of use.  The longitude of the central meridian ``+lon_0=90``, can also be expressed more explictly
with units of decimal degrees as ``+lon_0=90d`` or in radian
units as ``+lon_0=1.5708r`` (approximately).
```

2022-09-27 06:52 UTC, kbevers approved these changes
This looks great, thanks for brushing the docs up a bit

2022-09-27 06:52 UTC, sval-dev commented
Added some examples to the suggestion operation options.

2022-09-27 07:19 UTC, sval-dev commented
> This looks great, thanks for brushing the docs up a bit

Glad to help!

2022-09-27 09:44 UTC, merged