Update faq.rst to mention geod
OSGeo/proj.4 pull request #3895
Opened 2023-09-20 09:14 UTC by jidanni

See https://github.com/OSGeo/PROJ/issues/2644

2023-09-20 13:27 UTC, busstoptaktik requested changes
Needs some linguistic TLC

2023-09-20 13:27 UTC, busstoptaktik commented on docs/source/faq.rst
> +(And `geod`, which on the contrary expects latitude/longetude, and lacks any
\`geod\` should probably be :program:\`geod\`.

Also, putting an entire sentence in parenthesis looks strange, especially as it bumps oddly against the parenthesis at the end of the previous sentence. I suggest something like
```rst
... (unless :option:`proj -r` is used), while :program:`geod`,
on the contrary, expects latitude/longitude, and does not support the `-r` option.
```

Also note the correction longetude -> longitude

2023-09-22 09:20 UTC, jidanni commented
I'm very grateful for anybody to take this anywhere they want to.

Regarding minus r. Note that if such an option was added to geod, it should be a no-op. And then a different option added to accept lon lat.

And then after adding these options, the article might just complain about contrasting defaults, without mentioning  lack of options.

2023-09-22 09:33 UTC, jidanni commented
In https://github.com/OSGeo/PROJ/issues/2644#issuecomment-1731100116 I mention a scheme, where adding options to all the programs offered, could wallpaper over the worry about different defaults for different programs (that the PROJect distributes... Internal contradictions)

In fact the FAQ article could mention this scheme as a cherry note.

Of course implementing it: I'll leave that up to you guys :-)

2023-09-28 14:39 UTC, rouault commented on docs/source/faq.rst
> +(And `geod`, which on the contrary expects latitude/longetude, and lacks any
```suggestion
(And :program:`geod`, which on the contrary expects latitude/longitude, and lacks any
```

2023-09-30 13:31 UTC, merged