eqc documentation matching template (version 3)
OSGeo/proj.4 pull request #415
Opened 2016-09-15 22:40 UTC by julien2512

Here is the third version, matching the template proposal.

As I got a better understanding of proj4 implementation, I think there might be a mistake in eqc implementation.

In the description of wikipedia, nor wolfram, there is only one parameter \phi_ts. Evenden do not use any.
But in proj4, we got two : \phi_ts and \phi_0.

That's I tryed to document it on this pull request.
Although, I can't find how this value is valuated in proj4, and I find no documentation (wikipedia, evenden, wolfram, epsg) talking about a parameter phi_0 different than phi_ts.

May be phi_0 value is simply always 0 in proj4, and just leave in the code as a reminder ?

2016-09-15 23:33 UTC, QuLogic commented on docs/source/projections/eqc.rst
> +The simplist of all projections. Standard parallels (0° when omitted) may be specified that determine latitude of true scale (k=h=1).
simplest

2016-09-15 23:34 UTC, QuLogic commented on docs/source/projections/eqc.rst
>     :alt:   Equidistant Cylindrical (Plate Caree)
Carree, or even more correct, Carrée, especially because that's used later.

2016-09-15 23:36 UTC, QuLogic commented on docs/source/projections/eqc.rst
> +| Plain/Plane Chart                                       | 0◦                       |
This is the "White Bullet" symbol, not the degree sign, cf. ◦ vs. °.

2016-09-15 23:39 UTC, QuLogic commented on docs/source/projections/eqc.rst
> +| Ronald Miller—minimum overall scale distortion          | 37°30'                   |
The "apostrophe" should be a "prime", cf. ' vs. ′ (though I can't really see a difference with my default font here, so it's rather minor, and probably not a big deal.)

2016-09-15 23:42 UTC, QuLogic commented on docs/source/projections/eqc.rst
>  Equidistant Cylindrical (Plate Caree)
Carree or Carrée

2016-09-15 23:42 UTC, QuLogic requested changes
Mostly minor tweaks to stuff.

2016-09-16 09:02 UTC, kbevers commented on docs/source/projections/eqc.rst
> +
This section would be more clear if some of the variables are defined here. Like phi_ts is the latitude of true scale and can be set with +lat_ts.

2016-09-16 09:11 UTC, kbevers requested changes
Good work @julien2512. Thanks for doing this.

I've pointed out a few things I'd like to see adressed before I merge this. On top of this I think that @QuLogic has some valid points as well. 

Regarding the phi_0 variable. It is the latitude of origin and can be set with +lat_0.

2016-09-16 19:43 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +| **Implemented by**  | Marinus of Tyre                                          |
done.

2016-09-16 19:43 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +    223402.14       111701.07
Alright.

2016-09-16 19:46 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +| Ronald Miller—minimum overall scale distortion          | 37°30'                   |
Really ? I hope parser will recognise both.
done.

2016-09-16 19:48 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +| Plain/Plane Chart                                       | 0◦                       |
It was from the old doc !
done.

2016-09-16 19:49 UTC, julien2512 commented on docs/source/projections/eqc.rst
>     :alt:   Equidistant Cylindrical (Plate Caree)
Even better !
done.

2016-09-16 19:50 UTC, julien2512 commented on docs/source/projections/eqc.rst
>  Equidistant Cylindrical (Plate Caree)
There is a point here. The plate carrée is just one case of equidistant cylindrical, isn't it ? So why using it on the title ...

done.

2016-09-16 19:51 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +The simplist of all projections. Standard parallels (0° when omitted) may be specified that determine latitude of true scale (k=h=1).
done

2016-09-16 20:34 UTC, julien2512 commented
@kbevers 
> Regarding the phi_0 variable. It is the latitude of origin and can be set with +lat_0.

Can you help me to know where the lat_0 is taking a value in proj4 ? It can make me ask many less questions !

2016-09-16 20:45 UTC, kbevers commented
> Can you help me to know where the lat_0 is taking a value in proj4 ? It can make me ask many less questions !

Sure. It's done when calling pj_init. So when you initialize a projection.

2016-09-16 20:51 UTC, julien2512 commented
Thank you, I found :
`PIN->phi0 = pj_param(ctx, start, "rlat_0").f;`

2016-09-16 21:07 UTC, julien2512 commented
@QuLogic thank you for your help.

2016-09-16 21:18 UTC, julien2512 commented on docs/source/projections/eqc.rst
> +
I tryed something with the parameters.
Can you check it ? 
I feel it is important to evaluate the quality before stepping to an other projection doc.

2016-09-16 21:27 UTC, kbevers commented on docs/source/projections/eqc.rst
> +:math:`phi_{ts}` is the latitude of true scale, that mean the standard parallels where the scale of the projection is true. It can be set with "lat_ts".
I think there's backslash missing here.  Same for the line below.

2016-09-17 18:47 UTC, julien2512 commented
That is working for me without backslashes. Is there a better way to format
these  mines ?

Le 16 sept. 2016 23:27, "Kristian Evers" <notifications@github.com> a
écrit :

> *@kbevers* commented on this pull request.
> ------------------------------
>
> In docs/source/projections/eqc.rst
> <https://github.com/OSGeo/proj.4/pull/415#pullrequestreview-430686>:
>
> > @@ -71,8 +71,10 @@ Mathematical definition
>  #######################
>
>  The formulas describing the Equidistant Cylindrical projection are all taken from proj4 sources.
> -:math:`lat_ts` is the latitude of true scale, that mean the standard parallels where the scale of the projection is true.
> -:math:`lat_0` is the latitude of origin that match the center of the map.
> +
> +:math:`phi_{ts}` is the latitude of true scale, that mean the standard parallels where the scale of the projection is true. It can be set with "lat_ts".
>
> I think there's backslash missing here. Same for the line below.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OSGeo/proj.4/pull/415#pullrequestreview-430686>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAzLSQ-ruW5kSydrgrG3SYCDFZUQ7dTJks5qqwmugaJpZM4J-bev>
> .
>

2016-09-18 13:17 UTC, kbevers commented
Really? Do you build the docs with sphinx?

2016-09-21 20:45 UTC, julien2512 commented
Of course ! 
Eventhough, I am open to your proposal.

2016-09-22 06:36 UTC, kbevers commented
Great. I'll merge your PR once you change it.

2016-09-28 06:55 UTC, merged

2016-09-28 08:08 UTC, kbevers commented
Thanks for writing this, Julien. It is very much appreciated!

2016-09-28 20:36 UTC, julien2512 commented
Let's start other ones !

2016-09-28 20:59 UTC, julien2512 commented
It will be Cassini.

2018-04-08 17:55 UTC, Andre-J commented
There is a bug in the example: 
Example using Plate Carrée projection with true scale at latitude 30° and central meridian 90°W:
$ echo -88 30 | proj +proj=eqc +lat_ts=30 +lat_0=90w

Central meridian should be lon_0, which is not included in the formulas, but changing values for lon_0 different from zero resolves to different results. Seems that Proj can do more than Snyder wrote in his formulas. Maybe this should be pointed out on the manpage.

2018-04-09 00:07 UTC, kbevers commented
Good catch. Indeed it should be `+lon_0`. Fixed in https://github.com/OSGeo/proj.4/commit/89af2753651f8c21eae9df631a71c0a3b03bcc3b

> Seems that Proj can do more than Snyder wrote in his formulas. Maybe this should be pointed out on the manpage.

The `+lon_0` adjust the longitude before it reaches the projection fwd/inv functions, as seen here: https://github.com/OSGeo/proj.4/blob/84c2fed374da46ba0ca3cae1125350b1aa3f73fd/src/pj_fwd.c#L86

I agree that this should be documented better. It's on my list for the next large overhaul of the docs.