Miller projection doc first shot
OSGeo/proj.4 pull request #483
Opened 2017-01-29 22:20 UTC by julien2512

Miller projection doc first shot

2017-01-31 17:12 UTC, kbevers requested changes
A few very minor details, otherwise it's good. Thanks.

2017-01-31 17:12 UTC, kbevers commented on docs/source/projections/mill.rst
> +| **Available forms** | Forward and inverse Spherical                                                  |
"Spherical" should be all lower case

2017-01-31 17:12 UTC, kbevers commented on docs/source/projections/mill.rst
> +Spherical form
You could leave this out, since there the spherical form is the only one for this projection

2017-02-02 21:26 UTC, julien2512 commented on docs/source/projections/mill.rst
> +| **Available forms** | Forward and inverse Spherical                                                  |
Done

2017-02-02 21:26 UTC, julien2512 commented on docs/source/projections/mill.rst
> +Spherical form
Done

2017-02-02 21:27 UTC, julien2512 commented
It was an easy one indeed.

2017-02-03 10:05 UTC, kbevers approved these changes

2017-02-03 10:06 UTC, merged

2017-02-04 02:41 UTC, julien2512 commented
Next will be the "Cylindrical equal-area projection".